const isMongoConfigured = () => Boolean(process.env.MONGO_URI);

module.exports = {
  isDemoMode: () => !isMongoConfigured(),
  isMongoConfigured,
  demoAdminUser: () => ({
    _id: 'demo-admin',
    id: 'demo-admin',
    name: process.env.ADMIN_DEMO_NAME || 'Admin',
    email: process.env.ADMIN_DEMO_EMAIL || 'admin@prakriti.seva',
    phone: '',
    temple: '',
    role: 'admin',
    authProvider: 'local',
    profileImage: '',
    loginCount: 1,
    lastLoginAt: new Date(),
    createdAt: new Date(),
  }),
  demoUsers: () => ([
    {
      _id: 'demo-admin',
      name: process.env.ADMIN_DEMO_NAME || 'Admin',
      email: process.env.ADMIN_DEMO_EMAIL || 'admin@prakriti.seva',
      role: 'admin',
      points: 120,
      contributions: 80,
      temple: 'Prakriti Seva Temple',
      authProvider: 'local',
      createdAt: new Date().toISOString(),
      loginCount: 5,
    },
    {
      _id: 'demo-user-1',
      name: 'Eco Volunteer',
      email: 'volunteer@example.com',
      role: 'user',
      points: 42,
      contributions: 20,
      temple: 'Green Mandir',
      authProvider: 'local',
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      loginCount: 2,
    },
  ]),
  demoPickups: () => ([
    {
      _id: 'demo-pickup-1',
      temple: 'Prakriti Seva Temple',
      address: 'Demo Street 1',
      wasteType: 'Organic',
      scheduleDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
      contactNumber: '9999999999',
      quantity: 12,
      status: 'Pending',
      createdBy: { name: 'Eco Volunteer', email: 'volunteer@example.com' },
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'demo-pickup-2',
      temple: 'Green Mandir',
      address: 'Demo Street 2',
      wasteType: 'Plastic',
      scheduleDate: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
      contactNumber: '8888888888',
      quantity: 4,
      status: 'Approved',
      createdBy: { name: 'Eco Volunteer', email: 'volunteer@example.com' },
      createdAt: new Date().toISOString(),
    },
  ]),
  demoRewards: () => ([
    { _id: 'demo-reward-1', name: 'Seed Kit', pointsRequired: 25, stock: 10, isActive: true, createdAt: new Date().toISOString() },
    { _id: 'demo-reward-2', name: 'Cloth Bag', pointsRequired: 50, stock: 5, isActive: true, createdAt: new Date().toISOString() },
  ]),
  demoAwareness: () => ([
    { _id: 'demo-awareness-1', title: 'Reduce Waste', description: 'Sort and recycle properly.', type: 'story', link: '#', createdAt: new Date().toISOString() },
    { _id: 'demo-awareness-2', title: 'Reuse Ritual Items', description: 'Use eco-friendly ritual practices.', type: 'infographic', link: '#', createdAt: new Date().toISOString() },
  ]),
  demoRedemptions: () => ([
    {
      _id: 'demo-redemption-1',
      user: { name: 'Eco Volunteer', email: 'volunteer@example.com', temple: 'Green Mandir' },
      reward: { name: 'Seed Kit', pointsRequired: 25 },
      pointsSpent: 25,
      status: 'requested',
      createdAt: new Date().toISOString(),
    },
  ]),
};